### ISSUE TITLE
Failing test not being reported with retry

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#542]
With retry on, some tests are failing every time and yet Marathon reports 0 failed tests in both the HTML report and the XML JUnit report.

I believe the only relevant portion of my Marathonfile is this:

```yaml
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 3
```

Retry 3 times (runs 4 times), Raw "4 failed", actual failed: 0 (not reporting correctly)
![Screen Shot 2021-07-28 at 7 17 09 AM](https://user-images.githubusercontent.com/20119855/127402369-4b629816-6866-4a00-aedf-b070d3dd1b2e.png)

No retry (runs 1 time), Raw "1 failed", actual failed: 1 (reporting correctly)
![Screen Shot 2021-07-28 at 8 22 16 AM](https://user-images.githubusercontent.com/20119855/127402390-4e4043f5-3c7b-4a3f-b28c-c11383e51d26.png)

Only happens with retry on. Tested with retry set to 1 and 3. Only happens with a few failing tests out of hundreds.

Using Marathon 0.6.2, newest release as of July 2021.

**Comment by Malinskiy** [comment]
Already fixed by #535. Will be in the next release

**Comment by smugleafdev** [comment]
Great! Looking forward to it.

**Comment by langerhans** [comment]
Hey, not sure if I should make a new issue. I just upgraded to 0.7.0 and I still see this behaviour. 
```
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 4
```
```
1035 passed, 0 failed, 2 ignored tests
	Flakiness overhead: 181059ms
	Raw: 1035 passed, 15 failed, 2 ignored, 140 incomplete tests
[snip]
...Test#fails failed 5 time(s)
```
Any ideas?
